site_name: iolanta.tech
site_url: https://iolanta.tech
repo_url: https://github.com/iolanta-tech/iolanta-tech
repo_name: iolanta-tech
copyright: Copyright © 2023 iolanta.tech

markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.details
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - awesome-pages
  - iolanta
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python-requests.org/en/master/objects.inv
  - macros:
      on_error_fail: true
      modules:
        - macros

theme:
  name: material
  icon:
    admonitions:
      1: material/numeric-1-circle
      2: material/numeric-2-circle
      3: material/numeric-3-circle
      4: material/numeric-4-circle
      5: material/numeric-5-circle
      6: material/numeric-6-circle
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate
